language: node_js
node_js:
- 8.0.0
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
- export PATH=$HOME/.yarn/bin:$PATH
script:
- yarn build
before_deploy:
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis CI"
- rm -rf node_modules
- git add -A
- sh .push.sh deploy
deploy:
  provider: npm
  email: parker.casey@gmail.com
  api_key: ${NPM_TOKEN}
  skip_cleanup: true
  on:
    tags: true
    branches: releases 
    repo: etaletai13/desktop-interface
